DROP TABLE IF EXISTS task_status_history;
DROP TABLE IF EXISTS todo;

CREATE TABLE todo (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    details TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    due_date DATETIME,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status ENUM('ACTIVE', 'COMPLETED') DEFAULT 'ACTIVE',
    is_deleted TINYINT(1) DEFAULT 0
);

CREATE TABLE todo_status_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    todo_id BIGINT NOT NULL,
    status ENUM('ACTIVE', 'COMPLETED') NOT NULL,
    is_deleted TINYINT(1) DEFAULT 0,
    changed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (todo_id) REFERENCES todo(id)
);
